//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumbBuddy.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlumbBuddy.Localization.AppText", typeof(AppText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for Help.
        /// </summary>
        internal static string CatalogDisplay_AskForHelp {
            get {
                return ResourceManager.GetString("CatalogDisplay_AskForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to ask specifically for help with {0} in a Community Support venue..
        /// </summary>
        internal static string CatalogDisplay_AskForHelp_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_AskForHelp_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string CatalogDisplay_Dependencies {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dependency is missing!.
        /// </summary>
        internal static string CatalogDisplay_Dependencies_OpenCatalogEntry_Missing_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies_OpenCatalogEntry_Missing_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Catalog Entry.
        /// </summary>
        internal static string CatalogDisplay_Dependencies_OpenCatalogEntry_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies_OpenCatalogEntry_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependents.
        /// </summary>
        internal static string CatalogDisplay_Dependents {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Catalog Entry.
        /// </summary>
        internal static string CatalogDisplay_Dependents_OpenCatalogEntry_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependents_OpenCatalogEntry_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string CatalogDisplay_Files {
            get {
                return ResourceManager.GetString("CatalogDisplay_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods Folder Path.
        /// </summary>
        internal static string CatalogDisplay_Files_ModsFolderPath {
            get {
                return ResourceManager.GetString("CatalogDisplay_Files_ModsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View this File.
        /// </summary>
        internal static string CatalogDisplay_Files_ViewThisFile_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_Files_ViewThisFile_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://jamesturner.yt/disablepacks.
        /// </summary>
        internal static string CatalogDisplay_IncompatiblePack_GuidanceUrl {
            get {
                return ResourceManager.GetString("CatalogDisplay_IncompatiblePack_GuidanceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires that {1} is NOT installed. You DO have {1} installed. Click here to view information about how to remove or disable packs..
        /// </summary>
        internal static string CatalogDisplay_IncompatiblePack_Installed_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_IncompatiblePack_Installed_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires that {1} is NOT installed. You do not have {1} installed. Click here to view information about how to remove or disable packs..
        /// </summary>
        internal static string CatalogDisplay_IncompatiblePack_NotInstalled_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_IncompatiblePack_NotInstalled_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires that {1} is installed. You do have {1} installed. Click here to view the store page for {1}..
        /// </summary>
        internal static string CatalogDisplay_RequiredPack_Installed_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_RequiredPack_Installed_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires that {1} is installed. You do NOT have {1} installed. Click here to view the store page for {1}..
        /// </summary>
        internal static string CatalogDisplay_RequiredPack_NotInstalled_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_RequiredPack_NotInstalled_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Catalog.
        /// </summary>
        internal static string CatalogDisplay_SearchCatalog {
            get {
                return ResourceManager.GetString("CatalogDisplay_SearchCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods appear in your Catalog when creators have included manifests in them..
        /// </summary>
        internal static string CatalogDisplay_UserAssistanceNote {
            get {
                return ResourceManager.GetString("CatalogDisplay_UserAssistanceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Common_Browse_Ellipsis {
            get {
                return ResourceManager.GetString("Common_Browse_Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creators.
        /// </summary>
        internal static string Common_Creators {
            get {
                return ResourceManager.GetString("Common_Creators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Common_Select {
            get {
                return ResourceManager.GetString("Common_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Common_Url {
            get {
                return ResourceManager.GetString("Common_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Platform.
        /// </summary>
        internal static string FoldersSelector_DistributionPlatform {
            get {
                return ResourceManager.GetString("FoldersSelector_DistributionPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads Folder.
        /// </summary>
        internal static string FoldersSelector_DownloadsFolder {
            get {
                return ResourceManager.GetString("FoldersSelector_DownloadsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Folder.
        /// </summary>
        internal static string FoldersSelector_InstallationFolder {
            get {
                return ResourceManager.GetString("FoldersSelector_InstallationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple macOS.
        /// </summary>
        internal static string FoldersSelector_MacOS {
            get {
                return ResourceManager.GetString("FoldersSelector_MacOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But, ya know... 👉👈... I can make mistakes just like anyone else..
        /// </summary>
        internal static string FoldersSelector_ManualSelection_OnboardingHeading_1 {
            get {
                return ResourceManager.GetString("FoldersSelector_ManualSelection_OnboardingHeading_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change any of these if they&apos;re wrong..
        /// </summary>
        internal static string FoldersSelector_ManualSelection_OnboardingHeading_2 {
            get {
                return ResourceManager.GetString("FoldersSelector_ManualSelection_OnboardingHeading_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string FoldersSelector_OperatingSystem {
            get {
                return ResourceManager.GetString("FoldersSelector_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Paths.
        /// </summary>
        internal static string FoldersSelector_ResetPaths {
            get {
                return ResourceManager.GetString("FoldersSelector_ResetPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EA App.
        /// </summary>
        internal static string FoldersSelector_TheEAApp {
            get {
                return ResourceManager.GetString("FoldersSelector_TheEAApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sims 4 is installed..
        /// </summary>
        internal static string FoldersSelector_TS4_Installed {
            get {
                return ResourceManager.GetString("FoldersSelector_TS4_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sims 4 is not installed..
        /// </summary>
        internal static string FoldersSelector_TS4_NotInstalled {
            get {
                return ResourceManager.GetString("FoldersSelector_TS4_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data Folder.
        /// </summary>
        internal static string FoldersSelector_UserDataFolder {
            get {
                return ResourceManager.GetString("FoldersSelector_UserDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruh... 🤦... there&apos;s not even a folder there..
        /// </summary>
        internal static string FoldersSelector_ValidateFolder_DoesNotExist {
            get {
                return ResourceManager.GetString("FoldersSelector_ValidateFolder_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid The Sims 4 installation. 🙄.
        /// </summary>
        internal static string FoldersSelector_ValidateInstallationFolder_NoBinary {
            get {
                return ResourceManager.GetString("FoldersSelector_ValidateInstallationFolder_NoBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👏 Very ambitious for taking me right to your Mods folder, but I actually need your User Data Folder (go up one, please!)..
        /// </summary>
        internal static string FoldersSelector_ValidateUserDataFolder_ModsFolder {
            get {
                return ResourceManager.GetString("FoldersSelector_ValidateUserDataFolder_ModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, Silly! That&apos;s not your Sims 4 User Data Folder. 😏 Or you need to launch the game once and try again....
        /// </summary>
        internal static string FoldersSelector_ValidateUserDataFolder_NoOptionsIni {
            get {
                return ResourceManager.GetString("FoldersSelector_ValidateUserDataFolder_NoOptionsIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Steam.
        /// </summary>
        internal static string FoldersSelector_ValveSteam {
            get {
                return ResourceManager.GetString("FoldersSelector_ValveSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Windows.
        /// </summary>
        internal static string FoldersSelector_Windows {
            get {
                return ResourceManager.GetString("FoldersSelector_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Topography.
        /// </summary>
        internal static string HUD_AnalyzingTopography_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_AnalyzingTopography_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m taking a closer look at your package load order and reviewing how your mods are interacting with each other to see if I need to warn you about anything. 😏.
        /// </summary>
        internal static string HUD_AnalyzingTopography_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_AnalyzingTopography_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Byte Code Files.
        /// </summary>
        internal static string HUD_ByteCodeFiles_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_ByteCodeFiles_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the number of compiled Python byte code files I found in script archives in your Mods folder..
        /// </summary>
        internal static string HUD_ByteCodeFiles_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_ByteCodeFiles_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because Script Mods are disabled in your Game Options, these compiled Python byte code files will not be loaded and executed by The Sims 4..
        /// </summary>
        internal static string HUD_ByteCodeFiles_Tip_ModsDisabled {
            get {
                return ResourceManager.GetString("HUD_ByteCodeFiles_Tip_ModsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cataloging ETA.
        /// </summary>
        internal static string HUD_CatalogingETA_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_CatalogingETA_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is my best guess as to how much longer this process is going to take. It will fluctuate a bit as I progress, but less so as I near the end of the list of files..
        /// </summary>
        internal static string HUD_CatalogingETA_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_CatalogingETA_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimating.
        /// </summary>
        internal static string HUD_CatalogingETA_Tip_Estimating {
            get {
                return ResourceManager.GetString("HUD_CatalogingETA_Tip_Estimating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cataloging Mods.
        /// </summary>
        internal static string HUD_CatalogingMods_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_CatalogingMods_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m currently combing through the files in your Mods folder and scribbling down notes, don&apos;t mind me. 😏.
        /// </summary>
        internal static string HUD_CatalogingMods_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_CatalogingMods_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composing Manifests.
        /// </summary>
        internal static string HUD_ComposingManifests_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_ComposingManifests_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s probably best that I do not actively read your Mods folder while I&apos;m also... writing to it? I&apos;ll resume cataloging as soon as these manifests are written. 😏.
        /// </summary>
        internal static string HUD_ComposingManifests_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_ComposingManifests_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version.
        /// </summary>
        internal static string HUD_GameVersion_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_GameVersion_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the current version of The Sims 4 you have installed..
        /// </summary>
        internal static string HUD_GameVersion_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_GameVersion_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        internal static string HUD_Packages_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_Packages_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the number of packages I was able to catalog in your Mods folder..
        /// </summary>
        internal static string HUD_Packages_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_Packages_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because Mods are disabled in your Game Options, these packages will not be loaded by The Sims 4..
        /// </summary>
        internal static string HUD_Packages_Tip_Description_ModsDisabled {
            get {
                return ResourceManager.GetString("HUD_Packages_Tip_Description_ModsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Scripts.
        /// </summary>
        internal static string HUD_PythonScripts_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_PythonScripts_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;Creator&apos;s Note: While The Sims 4 will work with Python scripts, it does so by interpretting them. Maxis&apos; SmartSim engine &lt;strong&gt;does not&lt;/strong&gt; Just-in-Time compile Python scripts in script archives. This means they will underperform &lt;strong&gt;considerably&lt;/strong&gt;. If these are your script archives, strongly consider compiling their scripts to byte code using Python 3.7.&lt;/em&gt;.
        /// </summary>
        internal static string HUD_PythonScripts_Tip_CreatorsNote {
            get {
                return ResourceManager.GetString("HUD_PythonScripts_Tip_CreatorsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the number of &lt;strong&gt;uncompiled&lt;/strong&gt; Python scripts I found in script archives in your Mods folder..
        /// </summary>
        internal static string HUD_PythonScripts_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_PythonScripts_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string HUD_Resources_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_Resources_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the number of resources in the packages I was able to catalog in your Mods folder..
        /// </summary>
        internal static string HUD_Resources_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_Resources_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;Creator&apos;s Note: This sum does not account for resource overrides. It is a strict, &quot;dumb sum&quot;.&lt;/em&gt;.
        /// </summary>
        internal static string HUD_Resources_Tip_Description_CreatorsNote {
            get {
                return ResourceManager.GetString("HUD_Resources_Tip_Description_CreatorsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because Mods are disabled in your Game Options, these resources will not be loaded by The Sims 4..
        /// </summary>
        internal static string HUD_Resources_Tip_Description_ModsDisabled {
            get {
                return ResourceManager.GetString("HUD_Resources_Tip_Description_ModsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Archives.
        /// </summary>
        internal static string HUD_ScriptArchives_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_ScriptArchives_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the number of script archives I was able to catalog in your Mods folder..
        /// </summary>
        internal static string HUD_ScriptArchives_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_ScriptArchives_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because Script Mods are disabled in your Game Options, these script archives will not be opened and executed by The Sims 4..
        /// </summary>
        internal static string HUD_ScriptArchives_Tip_ModsDisabled {
            get {
                return ResourceManager.GetString("HUD_ScriptArchives_Tip_ModsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping.
        /// </summary>
        internal static string HUD_Sleeping_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_Sleeping_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s probably best that I do not actively read your Mods folder while you&apos;re playing to maximize your computer&apos;s resources for the game itself. I&apos;ll wake up as soon as you exit the game. 😏.
        /// </summary>
        internal static string HUD_Sleeping_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_Sleeping_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string HUD_Waiting_Tip_Caption {
            get {
                return ResourceManager.GetString("HUD_Waiting_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m just waiting for activity in your Mods folder to die down and then I&apos;ll have a look. 😏.
        /// </summary>
        internal static string HUD_Waiting_Tip_Description {
            get {
                return ResourceManager.GetString("HUD_Waiting_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sims 4.
        /// </summary>
        internal static string UserDataFolderName {
            get {
                return ResourceManager.GetString("UserDataFolderName", resourceCulture);
            }
        }
    }
}
