//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumbBuddy.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlumbBuddy.Localization.AppText", typeof(AppText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for Help.
        /// </summary>
        internal static string CatalogDisplay_AskForHelp {
            get {
                return ResourceManager.GetString("CatalogDisplay_AskForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to ask specifically for help with {0} in a Community Support venue..
        /// </summary>
        internal static string CatalogDisplay_AskForHelp_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_AskForHelp_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string CatalogDisplay_Dependencies {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creators.
        /// </summary>
        internal static string CatalogDisplay_Dependencies_Creators {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies_Creators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CatalogDisplay_Dependencies_Name {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dependency is missing!.
        /// </summary>
        internal static string CatalogDisplay_Dependencies_OpenCatalogEntry_Missing_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies_OpenCatalogEntry_Missing_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Catalog Entry.
        /// </summary>
        internal static string CatalogDisplay_Dependencies_OpenCatalogEntry_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies_OpenCatalogEntry_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string CatalogDisplay_Dependencies_Url {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependencies_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependents.
        /// </summary>
        internal static string CatalogDisplay_Dependents {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creators.
        /// </summary>
        internal static string CatalogDisplay_Dependents_Creators {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependents_Creators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CatalogDisplay_Dependents_Name {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependents_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Catalog Entry.
        /// </summary>
        internal static string CatalogDisplay_Dependents_OpenCatalogEntry_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependents_OpenCatalogEntry_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string CatalogDisplay_Dependents_URL {
            get {
                return ResourceManager.GetString("CatalogDisplay_Dependents_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string CatalogDisplay_Files {
            get {
                return ResourceManager.GetString("CatalogDisplay_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods Folder Path.
        /// </summary>
        internal static string CatalogDisplay_Files_ModsFolderPath {
            get {
                return ResourceManager.GetString("CatalogDisplay_Files_ModsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View this File.
        /// </summary>
        internal static string CatalogDisplay_Files_ViewThisFile_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_Files_ViewThisFile_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://jamesturner.yt/disablepacks.
        /// </summary>
        internal static string CatalogDisplay_IncompatiblePack_GuidanceUrl {
            get {
                return ResourceManager.GetString("CatalogDisplay_IncompatiblePack_GuidanceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires that {1} is NOT installed. You DO have {1} installed. Click here to view information about how to remove or disable packs..
        /// </summary>
        internal static string CatalogDisplay_IncompatiblePack_Installed_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_IncompatiblePack_Installed_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires that {1} is NOT installed. You do not have {1} installed. Click here to view information about how to remove or disable packs..
        /// </summary>
        internal static string CatalogDisplay_IncompatiblePack_NotInstalled_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_IncompatiblePack_NotInstalled_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires that {1} is installed. You do have {1} installed. Click here to view the store page for {1}..
        /// </summary>
        internal static string CatalogDisplay_RequiredPack_Installed_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_RequiredPack_Installed_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires that {1} is installed. You do NOT have {1} installed. Click here to view the store page for {1}..
        /// </summary>
        internal static string CatalogDisplay_RequiredPack_NotInstalled_Tip {
            get {
                return ResourceManager.GetString("CatalogDisplay_RequiredPack_NotInstalled_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Catalog.
        /// </summary>
        internal static string CatalogDisplay_SearchCatalog {
            get {
                return ResourceManager.GetString("CatalogDisplay_SearchCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods appear in your Catalog when creators have included manifests in them..
        /// </summary>
        internal static string CatalogDisplay_UserAssistanceNote {
            get {
                return ResourceManager.GetString("CatalogDisplay_UserAssistanceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sims 4.
        /// </summary>
        internal static string UserDataFolderName {
            get {
                return ResourceManager.GetString("UserDataFolderName", resourceCulture);
            }
        }
    }
}
