// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlumbBuddy.Data;

#nullable disable

namespace PlumbBuddy.Data.Migrations
{
    [DbContext(typeof(PbDbContext))]
    [Migration("20240929042523_ModelV1")]
    partial class ModelV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ModCreatorModManifest", b =>
                {
                    b.Property<long>("AttributedModsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttributedModsId", "CreatorsId");

                    b.HasIndex("CreatorsId");

                    b.ToTable("ModCreatorModManifest");
                });

            modelBuilder.Entity("ModCreatorRequiredMod", b =>
                {
                    b.Property<long>("AttributedRequiredModsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttributedRequiredModsId", "CreatorsId");

                    b.HasIndex("CreatorsId");

                    b.ToTable("ModCreatorRequiredMod");
                });

            modelBuilder.Entity("ModExclusivityModManifest", b =>
                {
                    b.Property<long>("ExclusivitiesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpecifiedByModManifestsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExclusivitiesId", "SpecifiedByModManifestsId");

                    b.HasIndex("SpecifiedByModManifestsId");

                    b.ToTable("ModExclusivityModManifest");
                });

            modelBuilder.Entity("ModFeatureModManifest", b =>
                {
                    b.Property<long>("FeaturesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpecifiedByModManifestsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeaturesId", "SpecifiedByModManifestsId");

                    b.HasIndex("SpecifiedByModManifestsId");

                    b.ToTable("ModFeatureModManifest");
                });

            modelBuilder.Entity("ModFeatureRequiredMod", b =>
                {
                    b.Property<long>("RequiredFeaturesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpecifiedByRequiredModsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequiredFeaturesId", "SpecifiedByRequiredModsId");

                    b.HasIndex("SpecifiedByRequiredModsId");

                    b.ToTable("ModFeatureRequiredMod");
                });

            modelBuilder.Entity("ModFileResourceTopologySnapshot", b =>
                {
                    b.Property<long>("ResourcesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TopologySnapshotsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourcesId", "TopologySnapshotsId");

                    b.HasIndex("TopologySnapshotsId");

                    b.ToTable("ModFileResourceTopologySnapshot");
                });

            modelBuilder.Entity("ModManifestHashRequiredMod", b =>
                {
                    b.Property<long>("DependentsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HashesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DependentsId", "HashesId");

                    b.HasIndex("HashesId");

                    b.ToTable("ModManifestHashRequiredMod");
                });

            modelBuilder.Entity("ModManifestPackCode", b =>
                {
                    b.Property<long>("RequiredByModsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RequiredPacksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequiredByModsId", "RequiredPacksId");

                    b.HasIndex("RequiredPacksId");

                    b.ToTable("ModManifestPackCode");
                });

            modelBuilder.Entity("PlumbBuddy.Data.FileOfInterest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("FilesOfInterest");
                });

            modelBuilder.Entity("PlumbBuddy.Data.HashResourceKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("KeyFullInstance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModManifestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModManifestId");

                    b.ToTable("HashResourceKeys");
                });

            modelBuilder.Entity("PlumbBuddy.Data.IntentionalOverride", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("KeyFullInstance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModManfiestId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ModManifestHashId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ModManifestKeyFullInstance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModManifestKeyGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModManifestKeyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModManfiestId");

                    b.HasIndex("ModManifestHashId");

                    b.ToTable("IntentionalOverrides");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModCreator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ModCreators");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModExclusivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModExclusivities");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModFeature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModFeatures");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AbsenceNoticed")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Creation")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastWrite")
                        .HasColumnType("TEXT");

                    b.Property<long>("ModFileHashId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModFileHashId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Path", "Creation", "LastWrite", "Size");

                    b.ToTable("ModFiles");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModFileHash", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ResourcesAndManifestCataloged")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("ModFileHashes");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModFileResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("KeyFullInstance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModFileHashId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModFileHashId");

                    b.ToTable("ModFileResources");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModManifest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CalculatedModManifestHashId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InscribedModManifestHashId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("KeyFullInstance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KeyGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KeyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModFileHashId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResourceHashStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TuningFullInstance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TuningName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedModManifestHashId");

                    b.HasIndex("InscribedModManifestHashId");

                    b.HasIndex("ModFileHashId")
                        .IsUnique();

                    b.ToTable("ModManifests");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModManifestHash", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ModManifestId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ModManifestId");

                    b.ToTable("ModManifestHashes");
                });

            modelBuilder.Entity("PlumbBuddy.Data.PackCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("PackCodes");
                });

            modelBuilder.Entity("PlumbBuddy.Data.RequiredMod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IgnoreIfHashAvailableId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IgnoreIfHashUnavailableId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IgnoreIfPackAvailableId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IgnoreIfPackUnavailableId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ManifestKeyFullInstance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManifestKeyGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManifestKeyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModManfiestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RequirementIdentifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IgnoreIfHashAvailableId");

                    b.HasIndex("IgnoreIfHashUnavailableId");

                    b.HasIndex("IgnoreIfPackAvailableId");

                    b.HasIndex("IgnoreIfPackUnavailableId");

                    b.HasIndex("ModManfiestId");

                    b.HasIndex("RequirementIdentifierId");

                    b.ToTable("RequiredMods");
                });

            modelBuilder.Entity("PlumbBuddy.Data.RequirementIdentifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("RequirementIdentifiers");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ScriptModArchiveEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long>("CompressedLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExternalAttributes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModFileHashId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SignedCrc32")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModFileHashId", "FullName")
                        .IsUnique();

                    b.ToTable("ScriptModArchiveEntries");
                });

            modelBuilder.Entity("PlumbBuddy.Data.TopologySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Taken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TopologySnapshots");
                });

            modelBuilder.Entity("ModCreatorModManifest", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModManifest", null)
                        .WithMany()
                        .HasForeignKey("AttributedModsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.ModCreator", null)
                        .WithMany()
                        .HasForeignKey("CreatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModCreatorRequiredMod", b =>
                {
                    b.HasOne("PlumbBuddy.Data.RequiredMod", null)
                        .WithMany()
                        .HasForeignKey("AttributedRequiredModsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.ModCreator", null)
                        .WithMany()
                        .HasForeignKey("CreatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModExclusivityModManifest", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModExclusivity", null)
                        .WithMany()
                        .HasForeignKey("ExclusivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.ModManifest", null)
                        .WithMany()
                        .HasForeignKey("SpecifiedByModManifestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModFeatureModManifest", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModFeature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.ModManifest", null)
                        .WithMany()
                        .HasForeignKey("SpecifiedByModManifestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModFeatureRequiredMod", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModFeature", null)
                        .WithMany()
                        .HasForeignKey("RequiredFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.RequiredMod", null)
                        .WithMany()
                        .HasForeignKey("SpecifiedByRequiredModsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModFileResourceTopologySnapshot", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModFileResource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("TopologySnapshotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModManifestHashRequiredMod", b =>
                {
                    b.HasOne("PlumbBuddy.Data.RequiredMod", null)
                        .WithMany()
                        .HasForeignKey("DependentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.ModManifestHash", null)
                        .WithMany()
                        .HasForeignKey("HashesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModManifestPackCode", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModManifest", null)
                        .WithMany()
                        .HasForeignKey("RequiredByModsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.PackCode", null)
                        .WithMany()
                        .HasForeignKey("RequiredPacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlumbBuddy.Data.HashResourceKey", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModManifest", "ModManifest")
                        .WithMany("HashResourceKeys")
                        .HasForeignKey("ModManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModManifest");
                });

            modelBuilder.Entity("PlumbBuddy.Data.IntentionalOverride", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModManifest", "ModManifest")
                        .WithMany("IntentionalOverrides")
                        .HasForeignKey("ModManfiestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.ModManifestHash", "ModManifestHash")
                        .WithMany("Overriders")
                        .HasForeignKey("ModManifestHashId");

                    b.Navigation("ModManifest");

                    b.Navigation("ModManifestHash");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModFile", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModFileHash", "ModFileHash")
                        .WithMany("ModFiles")
                        .HasForeignKey("ModFileHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModFileHash");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModFileResource", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModFileHash", "ModFileHash")
                        .WithMany("Resources")
                        .HasForeignKey("ModFileHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModFileHash");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModManifest", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModManifestHash", "CalculatedModFileHash")
                        .WithMany()
                        .HasForeignKey("CalculatedModManifestHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.ModManifestHash", "InscribedModManifestHash")
                        .WithMany()
                        .HasForeignKey("InscribedModManifestHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.ModFileHash", "ModFileHash")
                        .WithOne("ModManifest")
                        .HasForeignKey("PlumbBuddy.Data.ModManifest", "ModFileHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculatedModFileHash");

                    b.Navigation("InscribedModManifestHash");

                    b.Navigation("ModFileHash");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModManifestHash", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModManifest", null)
                        .WithMany("SubsumedHashes")
                        .HasForeignKey("ModManifestId");
                });

            modelBuilder.Entity("PlumbBuddy.Data.RequiredMod", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModManifestHash", "IgnoreIfHashAvailable")
                        .WithMany("DisqualifyingByPresence")
                        .HasForeignKey("IgnoreIfHashAvailableId");

                    b.HasOne("PlumbBuddy.Data.ModManifestHash", "IgnoreIfHashUnavailable")
                        .WithMany("DisqualifyingByAbsence")
                        .HasForeignKey("IgnoreIfHashUnavailableId");

                    b.HasOne("PlumbBuddy.Data.PackCode", "IgnoreIfPackAvailable")
                        .WithMany("DisqualifyingByPresence")
                        .HasForeignKey("IgnoreIfPackAvailableId");

                    b.HasOne("PlumbBuddy.Data.PackCode", "IgnoreIfPackUnavailable")
                        .WithMany("DisqualifyingByAbsence")
                        .HasForeignKey("IgnoreIfPackUnavailableId");

                    b.HasOne("PlumbBuddy.Data.ModManifest", "ModManifest")
                        .WithMany("RequiredMods")
                        .HasForeignKey("ModManfiestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.RequirementIdentifier", "RequirementIdentifier")
                        .WithMany("RequirementGroupMembers")
                        .HasForeignKey("RequirementIdentifierId");

                    b.Navigation("IgnoreIfHashAvailable");

                    b.Navigation("IgnoreIfHashUnavailable");

                    b.Navigation("IgnoreIfPackAvailable");

                    b.Navigation("IgnoreIfPackUnavailable");

                    b.Navigation("ModManifest");

                    b.Navigation("RequirementIdentifier");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ScriptModArchiveEntry", b =>
                {
                    b.HasOne("PlumbBuddy.Data.ModFileHash", "ModFileHash")
                        .WithMany("ScriptModArchiveEntries")
                        .HasForeignKey("ModFileHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModFileHash");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModFileHash", b =>
                {
                    b.Navigation("ModFiles");

                    b.Navigation("ModManifest");

                    b.Navigation("Resources");

                    b.Navigation("ScriptModArchiveEntries");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModManifest", b =>
                {
                    b.Navigation("HashResourceKeys");

                    b.Navigation("IntentionalOverrides");

                    b.Navigation("RequiredMods");

                    b.Navigation("SubsumedHashes");
                });

            modelBuilder.Entity("PlumbBuddy.Data.ModManifestHash", b =>
                {
                    b.Navigation("DisqualifyingByAbsence");

                    b.Navigation("DisqualifyingByPresence");

                    b.Navigation("Overriders");
                });

            modelBuilder.Entity("PlumbBuddy.Data.PackCode", b =>
                {
                    b.Navigation("DisqualifyingByAbsence");

                    b.Navigation("DisqualifyingByPresence");
                });

            modelBuilder.Entity("PlumbBuddy.Data.RequirementIdentifier", b =>
                {
                    b.Navigation("RequirementGroupMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
