// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlumbBuddy.Data.Chronicle;

#nullable disable

namespace PlumbBuddy.Data.Chronicle.Migrations
{
    [DbContext(typeof(ChronicleDbContext))]
    [Migration("20251128052533_ModelV3")]
    partial class ModelV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.ChroniclePropertySet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("BasisCreated")
                        .HasMaxLength(8)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<byte[]>("BasisNucleusId")
                        .HasMaxLength(8)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<byte[]>("BasisOriginalPackageSha256")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<byte[]>("Created")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<string>("GameNameOverride")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("NucleusId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ChroniclePropertySets");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.DisabledSavePackageSnapshotDefectType", b =>
                {
                    b.Property<int>("SavePackageSnapshotDefectType")
                        .HasColumnType("INTEGER");

                    b.HasKey("SavePackageSnapshotDefectType");

                    b.ToTable("DisabledSavePackageSnapshotDefectTypes");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.KnownSavePackageHash", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("KnownSavePackageHashes");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.ResourceSnapshotDelta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("CompressionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PatchZLib")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("SavePackageResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SavePackageSnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SavePackageResourceId");

                    b.HasIndex("SavePackageSnapshotId");

                    b.ToTable("ResourceSnapshotDeltas");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.SavePackageResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CompressionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentSize")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ContentZLib")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("SavePackageResources");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.SavePackageSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveHouseholdName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EnhancedSavePackageHashId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPlayedLotName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPlayedWorldName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OriginalSavePackageHashId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("WasLive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnhancedSavePackageHashId");

                    b.HasIndex("OriginalSavePackageHashId");

                    b.ToTable("SavePackageSnapshots");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.SavePackageSnapshotDefect", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SavePackageSnapshotDefectType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SavePackageSnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SavePackageSnapshotId");

                    b.ToTable("SavePackageSnapshotDefects");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.SnapshotModFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path", "LastWriteTime", "Size", "Sha256")
                        .IsUnique();

                    b.ToTable("SnapshotModFiles");
                });

            modelBuilder.Entity("SavePackageResourceSavePackageSnapshot", b =>
                {
                    b.Property<long>("ResourcesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SnapshotsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourcesId", "SnapshotsId");

                    b.HasIndex("SnapshotsId");

                    b.ToTable("SavePackageResourceSavePackageSnapshot");
                });

            modelBuilder.Entity("SavePackageSnapshotSnapshotModFile", b =>
                {
                    b.Property<long>("ModFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SnapshotsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModFilesId", "SnapshotsId");

                    b.HasIndex("SnapshotsId");

                    b.ToTable("SavePackageSnapshotSnapshotModFile");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.ResourceSnapshotDelta", b =>
                {
                    b.HasOne("PlumbBuddy.Data.Chronicle.SavePackageResource", "SavePackageResource")
                        .WithMany("Deltas")
                        .HasForeignKey("SavePackageResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.Chronicle.SavePackageSnapshot", "SavePackageSnapshot")
                        .WithMany("Deltas")
                        .HasForeignKey("SavePackageSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavePackageResource");

                    b.Navigation("SavePackageSnapshot");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.SavePackageSnapshot", b =>
                {
                    b.HasOne("PlumbBuddy.Data.Chronicle.KnownSavePackageHash", "EnhancedSavePackageHash")
                        .WithMany()
                        .HasForeignKey("EnhancedSavePackageHashId");

                    b.HasOne("PlumbBuddy.Data.Chronicle.KnownSavePackageHash", "OriginalSavePackageHash")
                        .WithMany()
                        .HasForeignKey("OriginalSavePackageHashId");

                    b.Navigation("EnhancedSavePackageHash");

                    b.Navigation("OriginalSavePackageHash");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.SavePackageSnapshotDefect", b =>
                {
                    b.HasOne("PlumbBuddy.Data.Chronicle.SavePackageSnapshot", "SavePackageSnapshot")
                        .WithMany("Defects")
                        .HasForeignKey("SavePackageSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavePackageSnapshot");
                });

            modelBuilder.Entity("SavePackageResourceSavePackageSnapshot", b =>
                {
                    b.HasOne("PlumbBuddy.Data.Chronicle.SavePackageResource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.Chronicle.SavePackageSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavePackageSnapshotSnapshotModFile", b =>
                {
                    b.HasOne("PlumbBuddy.Data.Chronicle.SnapshotModFile", null)
                        .WithMany()
                        .HasForeignKey("ModFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbBuddy.Data.Chronicle.SavePackageSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.SavePackageResource", b =>
                {
                    b.Navigation("Deltas");
                });

            modelBuilder.Entity("PlumbBuddy.Data.Chronicle.SavePackageSnapshot", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("Deltas");
                });
#pragma warning restore 612, 618
        }
    }
}
